[DEFAULT]
Delay=5
Dela2=15
balance_minimo = 0.00010001
Alternar = 1          # 0 = no, 1 = si
sleepMax=300
sleepMin=1
investment_amount = 100
minimun_profit = 3.00
currency=BTC
#currency=BNB
minumun_price=106403
#minumun_price=690
#currency=BTC
#currencyPair=LTCUSDT
currencyPair=BTCUSDT
#currencyPair=BNBUSDT
#currencybnbPair=BTCUSDT
